language: c

env:
   global:
     - R_BUILD_ARGS="--no-manual --no-build-vignettes"
     - R_CHECK_ARGS="--no-manual --no-build-vignettes"
     - BOOTSTRAP_LATEX="1"
     - WARNINGS_ARE_ERRORS=0

script: ./travis-tool.sh run_tests

before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_deps
